# coding: utf-8

"""
    OneLogin API

    This is an administrative API for OneLogin customers  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import onelogin
from onelogin.models.response_user import ResponseUser  # noqa: E501
from onelogin.rest import ApiException


class TestResponseUser(unittest.TestCase):
    """ResponseUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponseUser(self):
        """Test ResponseUser"""
        # FIXME: construct object with mandatory attributes with example values
        # model = onelogin.models.response_user.ResponseUser()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
