# coding: utf-8

"""
    OneLogin API

    This is an administrative API for OneLogin customers  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import onelogin
from onelogin.models.user_mfa_factors_response_data_auth_factors import UserMfaFactorsResponseDataAuthFactors  # noqa: E501
from onelogin.rest import ApiException


class TestUserMfaFactorsResponseDataAuthFactors(unittest.TestCase):
    """UserMfaFactorsResponseDataAuthFactors unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserMfaFactorsResponseDataAuthFactors(self):
        """Test UserMfaFactorsResponseDataAuthFactors"""
        # FIXME: construct object with mandatory attributes with example values
        # model = onelogin.models.user_mfa_factors_response_data_auth_factors.UserMfaFactorsResponseDataAuthFactors()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
