# coding: utf-8

"""
    OneLogin API

    This is an administrative API for OneLogin customers  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import onelogin
from onelogin.api.mfa_api import MfaApi  # noqa: E501
from onelogin.rest import ApiException


class TestMfaApi(unittest.TestCase):
    """MfaApi unit test stubs"""

    def setUp(self):
        self.api = onelogin.api.mfa_api.MfaApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_activate_user_mfa_device(self):
        """Test case for activate_user_mfa_device

        Activate an authentication factor  # noqa: E501
        """
        pass

    def test_delete_user_mfa_device(self):
        """Test case for delete_user_mfa_device

        Remove an authentication device  # noqa: E501
        """
        pass

    def test_enroll_user_mfa_device(self):
        """Test case for enroll_user_mfa_device

        Enroll a user with a given authentication factor.  # noqa: E501
        """
        pass

    def test_get_user_available_mfa_factors(self):
        """Test case for get_user_available_mfa_factors

        Get a list of MFA factors available to user  # noqa: E501
        """
        pass

    def test_get_user_enrolled_mfa_devices(self):
        """Test case for get_user_enrolled_mfa_devices

        Get enrolled authentication devices  # noqa: E501
        """
        pass

    def test_verify_user_mfa_device(self):
        """Test case for verify_user_mfa_device

        Verify an authentication device  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
