# coding: utf-8

"""
    OneLogin API

    This is an administrative API for OneLogin customers  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import onelogin
from onelogin.api.invites_api import InvitesApi  # noqa: E501
from onelogin.rest import ApiException


class TestInvitesApi(unittest.TestCase):
    """InvitesApi unit test stubs"""

    def setUp(self):
        self.api = onelogin.api.invites_api.InvitesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_invite_link(self):
        """Test case for create_invite_link

        Generate Invite Link  # noqa: E501
        """
        pass

    def test_send_invite_link(self):
        """Test case for send_invite_link

        Send Invite Link  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
