# coding: utf-8

"""
    OneLogin API

    This is an administrative API for OneLogin customers  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import onelogin
from onelogin.api.saml_api import SamlApi  # noqa: E501
from onelogin.rest import ApiException


class TestSamlApi(unittest.TestCase):
    """SamlApi unit test stubs"""

    def setUp(self):
        self.api = onelogin.api.saml_api.SamlApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_saml_assertion(self):
        """Test case for create_saml_assertion

        Generate SAML assertion  # noqa: E501
        """
        pass

    def test_verify_saml_assertion_mfa_token(self):
        """Test case for verify_saml_assertion_mfa_token

        Verify an MFA token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
