# coding: utf-8

"""
    OneLogin API

    This is an administrative API for OneLogin customers  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import onelogin
from onelogin.api.login_api import LoginApi  # noqa: E501
from onelogin.rest import ApiException


class TestLoginApi(unittest.TestCase):
    """LoginApi unit test stubs"""

    def setUp(self):
        self.api = onelogin.api.login_api.LoginApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_authenticate_user(self):
        """Test case for authenticate_user

        Authenticate a user  # noqa: E501
        """
        pass

    def test_verify_login_mfa_token(self):
        """Test case for verify_login_mfa_token

        Verify an MFA token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
