# coding: utf-8

"""
    OneLogin API

    This is an administrative API for OneLogin customers  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import onelogin
from onelogin.api.privileges_api import PrivilegesApi  # noqa: E501
from onelogin.rest import ApiException


class TestPrivilegesApi(unittest.TestCase):
    """PrivilegesApi unit test stubs"""

    def setUp(self):
        self.api = onelogin.api.privileges_api.PrivilegesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_privilege_roles(self):
        """Test case for add_privilege_roles

        Assign roles  # noqa: E501
        """
        pass

    def test_add_privilege_users(self):
        """Test case for add_privilege_users

        Assign users  # noqa: E501
        """
        pass

    def test_create_privilege(self):
        """Test case for create_privilege

        Creates privilege  # noqa: E501
        """
        pass

    def test_delete_privilege(self):
        """Test case for delete_privilege

        Delete privilege  # noqa: E501
        """
        pass

    def test_get_privilege(self):
        """Test case for get_privilege

        Get privilege  # noqa: E501
        """
        pass

    def test_get_privilege_roles(self):
        """Test case for get_privilege_roles

        Get roles  # noqa: E501
        """
        pass

    def test_get_privilege_users(self):
        """Test case for get_privilege_users

        Get privilege users  # noqa: E501
        """
        pass

    def test_get_privileges(self):
        """Test case for get_privileges

        Get Privileges  # noqa: E501
        """
        pass

    def test_remove_privilege_role(self):
        """Test case for remove_privilege_role

        Remove a role  # noqa: E501
        """
        pass

    def test_remove_privlege_user(self):
        """Test case for remove_privlege_user

        Remove a user  # noqa: E501
        """
        pass

    def test_update_privilege(self):
        """Test case for update_privilege

        Update privilege  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
