# coding: utf-8

"""
    OneLogin API

    This is an administrative API for OneLogin customers  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import onelogin
from onelogin.api.groups_api import GroupsApi  # noqa: E501
from onelogin.rest import ApiException


class TestGroupsApi(unittest.TestCase):
    """GroupsApi unit test stubs"""

    def setUp(self):
        self.api = onelogin.api.groups_api.GroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_group(self):
        """Test case for get_group

        Get Group by ID  # noqa: E501
        """
        pass

    def test_get_groups(self):
        """Test case for get_groups

        Get Groups  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
