# coding: utf-8

"""
    OneLogin API

    This is an administrative API for OneLogin customers  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import onelogin
from onelogin.api.users_api import UsersApi  # noqa: E501
from onelogin.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = onelogin.api.users_api.UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_user_roles(self):
        """Test case for add_user_roles

        Assign Role to User  # noqa: E501
        """
        pass

    def test_create_user(self):
        """Test case for create_user

        Create a User  # noqa: E501
        """
        pass

    def test_create_user_temp_mfa_token(self):
        """Test case for create_user_temp_mfa_token

        Generate Temp MFA Token  # noqa: E501
        """
        pass

    def test_delete_user(self):
        """Test case for delete_user

        Delete a user account  # noqa: E501
        """
        pass

    def test_get_custom_attributes(self):
        """Test case for get_custom_attributes

        Get Custom Attributes  # noqa: E501
        """
        pass

    def test_get_user(self):
        """Test case for get_user

        Get a User  # noqa: E501
        """
        pass

    def test_get_user_apps(self):
        """Test case for get_user_apps

        Get User Apps  # noqa: E501
        """
        pass

    def test_get_user_roles(self):
        """Test case for get_user_roles

        Get User Roles  # noqa: E501
        """
        pass

    def test_get_users(self):
        """Test case for get_users

        Get Users  # noqa: E501
        """
        pass

    def test_lock_user(self):
        """Test case for lock_user

        Lock a user account  # noqa: E501
        """
        pass

    def test_logout_user(self):
        """Test case for logout_user

        Log a user out of any and all sessions  # noqa: E501
        """
        pass

    def test_remove_user_roles(self):
        """Test case for remove_user_roles

        Remove Roles from User  # noqa: E501
        """
        pass

    def test_update_user(self):
        """Test case for update_user

        Update a User  # noqa: E501
        """
        pass

    def test_update_user_custom_attributes(self):
        """Test case for update_user_custom_attributes

        Set a custom attribute  # noqa: E501
        """
        pass

    def test_update_user_password(self):
        """Test case for update_user_password

        Set a the password for a user  # noqa: E501
        """
        pass

    def test_update_user_password_salted(self):
        """Test case for update_user_password_salted

        Set a pre salted password for a user  # noqa: E501
        """
        pass

    def test_update_user_state(self):
        """Test case for update_user_state

        Set the State for a user.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
