# coding: utf-8

"""
    OneLogin API

    This is an administrative API for OneLogin customers  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import onelogin
from onelogin.api.roles_api import RolesApi  # noqa: E501
from onelogin.rest import ApiException


class TestRolesApi(unittest.TestCase):
    """RolesApi unit test stubs"""

    def setUp(self):
        self.api = onelogin.api.roles_api.RolesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_role(self):
        """Test case for get_role

        Get Role by ID  # noqa: E501
        """
        pass

    def test_get_roles(self):
        """Test case for get_roles

        Get Roles  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
