# coding: utf-8

"""
    OneLogin API

    This is an administrative API for OneLogin customers  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import onelogin
from onelogin.models.user_login_request import UserLoginRequest  # noqa: E501
from onelogin.rest import ApiException


class TestUserLoginRequest(unittest.TestCase):
    """UserLoginRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserLoginRequest(self):
        """Test UserLoginRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = onelogin.models.user_login_request.UserLoginRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
