# coding: utf-8

"""
    OneLogin API

    This is an administrative API for OneLogin customers  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import onelogin
from onelogin.api.apps_api import AppsApi  # noqa: E501
from onelogin.rest import ApiException


class TestAppsApi(unittest.TestCase):
    """AppsApi unit test stubs"""

    def setUp(self):
        self.api = onelogin.api.apps_api.AppsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_app(self):
        """Test case for create_app

        Create an App  # noqa: E501
        """
        pass

    def test_delete_app(self):
        """Test case for delete_app

        Delete an app  # noqa: E501
        """
        pass

    def test_delete_app_parameter(self):
        """Test case for delete_app_parameter

        Delete an app parameter  # noqa: E501
        """
        pass

    def test_get_app(self):
        """Test case for get_app

        Get an App  # noqa: E501
        """
        pass

    def test_get_apps(self):
        """Test case for get_apps

        Get Apps  # noqa: E501
        """
        pass

    def test_update_app(self):
        """Test case for update_app

        Update an App  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
