# coding: utf-8

"""
    OneLogin API

    This is an administrative API for OneLogin customers  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from onelogin.configuration import Configuration


class AppInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'visible': 'bool',
        'description': 'str',
        'icon_url': 'str',
        'auth_method': 'int',
        'connector_id': 'int',
        'created_at': 'datetime',
        'updated_at': 'datetime'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'visible': 'visible',
        'description': 'description',
        'icon_url': 'icon_url',
        'auth_method': 'auth_method',
        'connector_id': 'connector_id',
        'created_at': 'created_at',
        'updated_at': 'updated_at'
    }

    def __init__(self, id=None, name=None, visible=None, description=None, icon_url=None, auth_method=None, connector_id=None, created_at=None, updated_at=None, _configuration=None):  # noqa: E501
        """AppInfo - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._name = None
        self._visible = None
        self._description = None
        self._icon_url = None
        self._auth_method = None
        self._connector_id = None
        self._created_at = None
        self._updated_at = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if visible is not None:
            self.visible = visible
        if description is not None:
            self.description = description
        if icon_url is not None:
            self.icon_url = icon_url
        if auth_method is not None:
            self.auth_method = auth_method
        if connector_id is not None:
            self.connector_id = connector_id
        if created_at is not None:
            self.created_at = created_at
        if updated_at is not None:
            self.updated_at = updated_at

    @property
    def id(self):
        """Gets the id of this AppInfo.  # noqa: E501


        :return: The id of this AppInfo.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AppInfo.


        :param id: The id of this AppInfo.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this AppInfo.  # noqa: E501


        :return: The name of this AppInfo.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AppInfo.


        :param name: The name of this AppInfo.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def visible(self):
        """Gets the visible of this AppInfo.  # noqa: E501


        :return: The visible of this AppInfo.  # noqa: E501
        :rtype: bool
        """
        return self._visible

    @visible.setter
    def visible(self, visible):
        """Sets the visible of this AppInfo.


        :param visible: The visible of this AppInfo.  # noqa: E501
        :type: bool
        """

        self._visible = visible

    @property
    def description(self):
        """Gets the description of this AppInfo.  # noqa: E501


        :return: The description of this AppInfo.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this AppInfo.


        :param description: The description of this AppInfo.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def icon_url(self):
        """Gets the icon_url of this AppInfo.  # noqa: E501


        :return: The icon_url of this AppInfo.  # noqa: E501
        :rtype: str
        """
        return self._icon_url

    @icon_url.setter
    def icon_url(self, icon_url):
        """Sets the icon_url of this AppInfo.


        :param icon_url: The icon_url of this AppInfo.  # noqa: E501
        :type: str
        """

        self._icon_url = icon_url

    @property
    def auth_method(self):
        """Gets the auth_method of this AppInfo.  # noqa: E501


        :return: The auth_method of this AppInfo.  # noqa: E501
        :rtype: int
        """
        return self._auth_method

    @auth_method.setter
    def auth_method(self, auth_method):
        """Sets the auth_method of this AppInfo.


        :param auth_method: The auth_method of this AppInfo.  # noqa: E501
        :type: int
        """

        self._auth_method = auth_method

    @property
    def connector_id(self):
        """Gets the connector_id of this AppInfo.  # noqa: E501


        :return: The connector_id of this AppInfo.  # noqa: E501
        :rtype: int
        """
        return self._connector_id

    @connector_id.setter
    def connector_id(self, connector_id):
        """Sets the connector_id of this AppInfo.


        :param connector_id: The connector_id of this AppInfo.  # noqa: E501
        :type: int
        """

        self._connector_id = connector_id

    @property
    def created_at(self):
        """Gets the created_at of this AppInfo.  # noqa: E501


        :return: The created_at of this AppInfo.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this AppInfo.


        :param created_at: The created_at of this AppInfo.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this AppInfo.  # noqa: E501


        :return: The updated_at of this AppInfo.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this AppInfo.


        :param updated_at: The updated_at of this AppInfo.  # noqa: E501
        :type: datetime
        """

        self._updated_at = updated_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AppInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AppInfo):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AppInfo):
            return True

        return self.to_dict() != other.to_dict()
