# coding: utf-8

"""
    OneLogin API

    This is an administrative API for OneLogin customers  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from onelogin.configuration import Configuration


class EnrollMfaDeviceRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'factor_id': 'int',
        'display_name': 'str',
        'number': 'str'
    }

    attribute_map = {
        'factor_id': 'factor_id',
        'display_name': 'display_name',
        'number': 'number'
    }

    def __init__(self, factor_id=None, display_name=None, number=None, _configuration=None):  # noqa: E501
        """EnrollMfaDeviceRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._factor_id = None
        self._display_name = None
        self._number = None
        self.discriminator = None

        self.factor_id = factor_id
        self.display_name = display_name
        self.number = number

    @property
    def factor_id(self):
        """Gets the factor_id of this EnrollMfaDeviceRequest.  # noqa: E501

        The identifier of the factor to enroll the user with  # noqa: E501

        :return: The factor_id of this EnrollMfaDeviceRequest.  # noqa: E501
        :rtype: int
        """
        return self._factor_id

    @factor_id.setter
    def factor_id(self, factor_id):
        """Sets the factor_id of this EnrollMfaDeviceRequest.

        The identifier of the factor to enroll the user with  # noqa: E501

        :param factor_id: The factor_id of this EnrollMfaDeviceRequest.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and factor_id is None:
            raise ValueError("Invalid value for `factor_id`, must not be `None`")  # noqa: E501

        self._factor_id = factor_id

    @property
    def display_name(self):
        """Gets the display_name of this EnrollMfaDeviceRequest.  # noqa: E501

        A name for the users device  # noqa: E501

        :return: The display_name of this EnrollMfaDeviceRequest.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this EnrollMfaDeviceRequest.

        A name for the users device  # noqa: E501

        :param display_name: The display_name of this EnrollMfaDeviceRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and display_name is None:
            raise ValueError("Invalid value for `display_name`, must not be `None`")  # noqa: E501

        self._display_name = display_name

    @property
    def number(self):
        """Gets the number of this EnrollMfaDeviceRequest.  # noqa: E501

        The phone number of the user in E.164 format.  # noqa: E501

        :return: The number of this EnrollMfaDeviceRequest.  # noqa: E501
        :rtype: str
        """
        return self._number

    @number.setter
    def number(self, number):
        """Sets the number of this EnrollMfaDeviceRequest.

        The phone number of the user in E.164 format.  # noqa: E501

        :param number: The number of this EnrollMfaDeviceRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and number is None:
            raise ValueError("Invalid value for `number`, must not be `None`")  # noqa: E501

        self._number = number

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EnrollMfaDeviceRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EnrollMfaDeviceRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EnrollMfaDeviceRequest):
            return True

        return self.to_dict() != other.to_dict()
