# coding: utf-8

"""
    OneLogin API

    This is an administrative API for OneLogin customers  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from onelogin.configuration import Configuration


class GenerateMfaTokenResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'reusable': 'bool',
        'mfa_token': 'str',
        'expires_at': 'datetime'
    }

    attribute_map = {
        'reusable': 'reusable',
        'mfa_token': 'mfa_token',
        'expires_at': 'expires_at'
    }

    def __init__(self, reusable=None, mfa_token=None, expires_at=None, _configuration=None):  # noqa: E501
        """GenerateMfaTokenResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._reusable = None
        self._mfa_token = None
        self._expires_at = None
        self.discriminator = None

        if reusable is not None:
            self.reusable = reusable
        if mfa_token is not None:
            self.mfa_token = mfa_token
        if expires_at is not None:
            self.expires_at = expires_at

    @property
    def reusable(self):
        """Gets the reusable of this GenerateMfaTokenResponse.  # noqa: E501


        :return: The reusable of this GenerateMfaTokenResponse.  # noqa: E501
        :rtype: bool
        """
        return self._reusable

    @reusable.setter
    def reusable(self, reusable):
        """Sets the reusable of this GenerateMfaTokenResponse.


        :param reusable: The reusable of this GenerateMfaTokenResponse.  # noqa: E501
        :type: bool
        """

        self._reusable = reusable

    @property
    def mfa_token(self):
        """Gets the mfa_token of this GenerateMfaTokenResponse.  # noqa: E501


        :return: The mfa_token of this GenerateMfaTokenResponse.  # noqa: E501
        :rtype: str
        """
        return self._mfa_token

    @mfa_token.setter
    def mfa_token(self, mfa_token):
        """Sets the mfa_token of this GenerateMfaTokenResponse.


        :param mfa_token: The mfa_token of this GenerateMfaTokenResponse.  # noqa: E501
        :type: str
        """

        self._mfa_token = mfa_token

    @property
    def expires_at(self):
        """Gets the expires_at of this GenerateMfaTokenResponse.  # noqa: E501


        :return: The expires_at of this GenerateMfaTokenResponse.  # noqa: E501
        :rtype: datetime
        """
        return self._expires_at

    @expires_at.setter
    def expires_at(self, expires_at):
        """Sets the expires_at of this GenerateMfaTokenResponse.


        :param expires_at: The expires_at of this GenerateMfaTokenResponse.  # noqa: E501
        :type: datetime
        """

        self._expires_at = expires_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GenerateMfaTokenResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GenerateMfaTokenResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GenerateMfaTokenResponse):
            return True

        return self.to_dict() != other.to_dict()
