# coding: utf-8

"""
    OneLogin API

    This is an administrative API for OneLogin customers  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from onelogin.configuration import Configuration


class GenerateMfaTokenRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'expires_in': 'int',
        'reusable': 'bool'
    }

    attribute_map = {
        'expires_in': 'expires_in',
        'reusable': 'reusable'
    }

    def __init__(self, expires_in=None, reusable=None, _configuration=None):  # noqa: E501
        """GenerateMfaTokenRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._expires_in = None
        self._reusable = None
        self.discriminator = None

        if expires_in is not None:
            self.expires_in = expires_in
        if reusable is not None:
            self.reusable = reusable

    @property
    def expires_in(self):
        """Gets the expires_in of this GenerateMfaTokenRequest.  # noqa: E501

        Set the duration of the token in seconds.  # noqa: E501

        :return: The expires_in of this GenerateMfaTokenRequest.  # noqa: E501
        :rtype: int
        """
        return self._expires_in

    @expires_in.setter
    def expires_in(self, expires_in):
        """Sets the expires_in of this GenerateMfaTokenRequest.

        Set the duration of the token in seconds.  # noqa: E501

        :param expires_in: The expires_in of this GenerateMfaTokenRequest.  # noqa: E501
        :type: int
        """

        self._expires_in = expires_in

    @property
    def reusable(self):
        """Gets the reusable of this GenerateMfaTokenRequest.  # noqa: E501

        Defines if the token is reusable multiple times within the expiry window.  # noqa: E501

        :return: The reusable of this GenerateMfaTokenRequest.  # noqa: E501
        :rtype: bool
        """
        return self._reusable

    @reusable.setter
    def reusable(self, reusable):
        """Sets the reusable of this GenerateMfaTokenRequest.

        Defines if the token is reusable multiple times within the expiry window.  # noqa: E501

        :param reusable: The reusable of this GenerateMfaTokenRequest.  # noqa: E501
        :type: bool
        """

        self._reusable = reusable

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GenerateMfaTokenRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GenerateMfaTokenRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GenerateMfaTokenRequest):
            return True

        return self.to_dict() != other.to_dict()
