# coding: utf-8

"""
    OneLogin API

    This is an administrative API for OneLogin customers  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from onelogin.configuration import Configuration


class VerifyMfaDeviceRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'otp_token': 'int',
        'state_token': 'str'
    }

    attribute_map = {
        'otp_token': 'otp_token',
        'state_token': 'state_token'
    }

    def __init__(self, otp_token=None, state_token=None, _configuration=None):  # noqa: E501
        """VerifyMfaDeviceRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._otp_token = None
        self._state_token = None
        self.discriminator = None

        if otp_token is not None:
            self.otp_token = otp_token
        if state_token is not None:
            self.state_token = state_token

    @property
    def otp_token(self):
        """Gets the otp_token of this VerifyMfaDeviceRequest.  # noqa: E501

        OTP code provided by the device or SMS message sent to user.  # noqa: E501

        :return: The otp_token of this VerifyMfaDeviceRequest.  # noqa: E501
        :rtype: int
        """
        return self._otp_token

    @otp_token.setter
    def otp_token(self, otp_token):
        """Sets the otp_token of this VerifyMfaDeviceRequest.

        OTP code provided by the device or SMS message sent to user.  # noqa: E501

        :param otp_token: The otp_token of this VerifyMfaDeviceRequest.  # noqa: E501
        :type: int
        """

        self._otp_token = otp_token

    @property
    def state_token(self):
        """Gets the state_token of this VerifyMfaDeviceRequest.  # noqa: E501

        The state_token is returned after a successful request to Enroll a Factor or Activate a Factor. The state_token MUST be provided if the needs_trigger attribute from the proceeding calls is set to true.  # noqa: E501

        :return: The state_token of this VerifyMfaDeviceRequest.  # noqa: E501
        :rtype: str
        """
        return self._state_token

    @state_token.setter
    def state_token(self, state_token):
        """Sets the state_token of this VerifyMfaDeviceRequest.

        The state_token is returned after a successful request to Enroll a Factor or Activate a Factor. The state_token MUST be provided if the needs_trigger attribute from the proceeding calls is set to true.  # noqa: E501

        :param state_token: The state_token of this VerifyMfaDeviceRequest.  # noqa: E501
        :type: str
        """

        self._state_token = state_token

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VerifyMfaDeviceRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VerifyMfaDeviceRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, VerifyMfaDeviceRequest):
            return True

        return self.to_dict() != other.to_dict()
