# coding: utf-8

"""
    OneLogin API

    This is an administrative API for OneLogin customers  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from onelogin.api_client import ApiClient


class SamlApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def create_saml_assertion(self, **kwargs):  # noqa: E501
        """Generate SAML assertion  # noqa: E501

        Use this API to generate a SAML assertion.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_saml_assertion(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param SamlAssertionRequest saml_assertion_request:
        :return: SamlAssertionResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.create_saml_assertion_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.create_saml_assertion_with_http_info(**kwargs)  # noqa: E501
            return data

    def create_saml_assertion_with_http_info(self, **kwargs):  # noqa: E501
        """Generate SAML assertion  # noqa: E501

        Use this API to generate a SAML assertion.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_saml_assertion_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param SamlAssertionRequest saml_assertion_request:
        :return: SamlAssertionResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['saml_assertion_request']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_saml_assertion" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'saml_assertion_request' in params:
            body_params = params['saml_assertion_request']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['application']  # noqa: E501

        return self.api_client.call_api(
            '/1/saml_assertion', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SamlAssertionResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def verify_saml_assertion_mfa_token(self, **kwargs):  # noqa: E501
        """Verify an MFA token  # noqa: E501

        Verify a one-time password (OTP) value, provided for a second factor, when multi-factor authentication (MFA) is required for SAML authentication.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.verify_saml_assertion_mfa_token(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param SamlVerifyMfaRequest saml_verify_mfa_request:
        :return: SamlAssertionResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.verify_saml_assertion_mfa_token_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.verify_saml_assertion_mfa_token_with_http_info(**kwargs)  # noqa: E501
            return data

    def verify_saml_assertion_mfa_token_with_http_info(self, **kwargs):  # noqa: E501
        """Verify an MFA token  # noqa: E501

        Verify a one-time password (OTP) value, provided for a second factor, when multi-factor authentication (MFA) is required for SAML authentication.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.verify_saml_assertion_mfa_token_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param SamlVerifyMfaRequest saml_verify_mfa_request:
        :return: SamlAssertionResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['saml_verify_mfa_request']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method verify_saml_assertion_mfa_token" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'saml_verify_mfa_request' in params:
            body_params = params['saml_verify_mfa_request']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['application']  # noqa: E501

        return self.api_client.call_api(
            '/1/saml_assertion/verify_factor', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SamlAssertionResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
